### ISSUE TITLE
Template transpiling node modules folder

### ISSUE THREAD

**Issue by antoniojunyor** [astrocket/rails-template#2]
How can I configure the template for don't do that?

I'm having some problem with `mapbox-gl` package.
https://github.com/mapbox/mapbox-gl-js/issues/3422

**Comment by astrocket** [comment]
@antoniojunyor 

Sorry for the late reply, I missed your issue.
You should try again with the updated source.

**Comment by antoniojunyor** [comment]
Thanks @astrocket
